### ISSUE TITLE
[UX] Show a progress bar on loading - Need API estimate

### ISSUE THREAD

**Issue by yomguy** [Ircam-Web/timeside-player#89]
An implementation example of a notification system using django-channels:

https://realpython.com/getting-started-with-django-channels/

**Comment by gnuletik** [comment]
IMO the challenge is how can we implement this progression on the API's async task (transcoding, analyzing) rather than how to do it with Django. But that's good to keep this nice resource :)

Also, can you transfer the issue on https://github.com/Parisson/TimeSide ? First, we have to implement this feature on the API.
I don't have the admin permission on this repository.

Thanks !

**Comment by yomguy** [comment]
@gnuletik now you have admin access to the TS repo.

**Comment by gnuletik** [comment]
Thanks @yomguy .

It seems that
> You can only transfer issues between repositories owned by the same user or organization account. You can't transfer an issue from a private repository to a public repository.

cf https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

So, I've copied the content on the other repo : https://github.com/Parisson/TimeSide/issues/198

Thanks !
